apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-01
provisioner: k8s-nfs-provisioner-01 # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
