apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: ng123
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.3
        volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: nginx
        nfs:
          server: 192.168.65.50
          path: /nfs/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
spec:
  selector: 
    app: nginx
  type: NodePort  
  ports:
    - port: 80
  
  