apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-nfs-storage-class
provisioner: k8s-nfs-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-nfs-persistent-volume-claim
spec:
  storageClassName: mysql-nfs-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
