apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: default
  labels:
    app: redis
data:
  redis.conf: |
    protected-mode no
    port 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.4
          imagePullPolicy: IfNotPresent
          command: ["redis-server","/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-map
              mountPath: /redis
      volumes:
        - name: config-map
          configMap:
            name: redis-configmap
