apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: default
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
    name: mysql-master
  clusterIP: None
  selector:
    app: mysql-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: default
  labels:
    app: mysql-master
spec:
  serviceName: "mysql-master"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels: 
        app: mysql-master
    spec:
      initContainers:
      - name: init-mysql-master
        image: mysql:8.0.29
        command:
          - bash
          - "-c"
          - |
            set -ex
            cp /mnt/config-map/master.cnf /mnt/conf.d/
            cp /mnt/config-map/mysql.cnf /mnt/conf.d/
        volumeMounts:
          - name: conf
            mountPath: /mnt/conf.d
          - name: config-map
            mountPath: /mnt/config-map
      containers:
      - name: mysql-master
        image: mysql:8.0.29
#        command:
#          - bash
#          - "-c"
#          - |
#            set -ex
#            mysql -h 127.0.0.1 -uroot -pmysql -e "CREATE USER 'slave'@'%' IDENTIFIED WITH mysql_native_password BY 'slave';GRANT REPLICATION SLAVE,REPLICATION CLIENT ON *.* TO 'slave'@'%';FLUSH PRIVILEGES;"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-nfs-master
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
      volumes:
        - name: config-map
          configMap:
            name: mysql-configmap
        - name: mysql-nfs-master
          persistentVolumeClaim:
            claimName: mysql-master-pvc
        - name: conf
          emptyDir: {}
      livenessProbe:
        exec:
          command: [ "mysqladmin", "ping" ]
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        exec:
          # Check we can execute queries over TCP (skip-networking is off).
          command: [ "mysql", "-h", "127.0.0.1", "-e", "SELECT 1" ]
        initialDelaySeconds: 5
        periodSeconds: 2
        timeoutSeconds: 1