kind: Pod
apiVersion: v1
metadata:
  name: mysql-init
spec:
  containers:
    - name: mysql-init
      image: mysql:8.0.29
      command:
        - bash
        - "-c"
        - |
          set -ex
          mysql -h mysql-master-0.mysql-master.default.svc.cluster.local -uroot -pmysql -e "CREATE USER 'slave'@'%' IDENTIFIED WITH mysql_native_password BY 'slave';GRANT REPLICATION SLAVE,REPLICATION CLIENT ON *.* TO 'slave'@'%';FLUSH PRIVILEGES;"
          BINLOG_FILE=`mysql -h mysql-master-0.mysql-master.default.svc.cluster.local -uslave -pslave -e "show master status" |awk '{if(NR==2)print $1}'`
          BINLOG_POS=`mysql -h mysql-master-0.mysql-master.default.svc.cluster.local -uslave -pslave -e "show master status" |awk '{if(NR==2)print $2}'`
          mysql -h mysql-slave-0.mysql-slave.default.svc.cluster.local -uroot -pmysql -e "CHANGE MASTER TO MASTER_HOST='mysql-master-0.mysql-master.default.svc.cluster.local',MASTER_USER='slave',MASTER_PASSWORD='slave',MASTER_LOG_FILE='$BINLOG_FILE',MASTER_LOG_POS=$BINLOG_POS;start slave;"
  restartPolicy: "Never"

