apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: default
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
    name: mysql-master
  clusterIP: None
  selector:
    app: mysql-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: default
  labels:
    app: mysql-master
spec:
  serviceName: "mysql-master"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels: 
        app: mysql-master
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.29
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
  volumeClaimTemplates:
  - metadata:
      name: mysql-master
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: mysql-nfs-storage
      resources:
        requests:
          storage: 500Mi